### ISSUE TITLE
User with permissions cannot see Netbox Tunnels plugin

### ISSUE THREAD

**Issue by ML-SRT** [robertlynch3/netbox-tunnels2#11]
**NetBox version**
What version of NetBox are you currently running? v3.5.3

**Describe the bug**
netbox-tunnels2 plugin only showing for super user

**To Reproduce**
Home > Authentication and Authorization > Users
Select user
Permissions > Add another permission
Name = Tunnels
Actions  = Can view, can add, can change, can delete
Objects > Object types > select Network Tunnels and Tunnel Type
Save
Save user

**Expected behavior**
User should see Network Tunnels under Plugins

**Screenshots**
Super user:
![image](https://github.com/robertlynch3/netbox-tunnels2/assets/107609939/ab983a27-7985-4dd6-8a52-287c1dc46be5)

User with permissions:
![image](https://github.com/robertlynch3/netbox-tunnels2/assets/107609939/d703f260-7323-45ce-8cf8-924b4702ca54)

![image](https://github.com/robertlynch3/netbox-tunnels2/assets/107609939/3792aeb3-0db1-4cf2-9f23-a4a7d6717f94)

**Additional context**
It is available for superuser but cannot get it for a standard user.

**Comment by robertlynch3** [comment]
I need to dive into this. I don't know the ins and outs of permissions beyond what the plugin tutorial has.

**Comment by johan-kummeneje-complior** [comment]
I've got the same issue in 3.5.7 and in essence, it just doesn't show the Plugin section. If I paste the URL's the pages shows for users. 
I think it may be that you are using PluginMenuButtons in navigation.py while others use pluginMenuItem.

**Comment by robertlynch3** [comment]
> I think it may be that you are using PluginMenuButtons in navigation.py while others use pluginMenuItem.

I don't believe this is the issue. The PluginMenuButton consists of a PluginMenuItem. The [code in this project](https://github.com/robertlynch3/netbox-tunnels2/blob/dc94e4d309ca762b56c773310b53791d4f9517b2/netbox_tunnels2/navigation.py#L18-L28) seems to match the code in [Netbox ACLs](https://github.com/ryanmerolle/netbox-acls/blob/adefefe9b1ca91f42352a3c7dd9682df54d15e6d/netbox_acls/navigation.py#L15-L28).



I think this has to do with this line
https://github.com/robertlynch3/netbox-tunnels2/blob/dc94e4d309ca762b56c773310b53791d4f9517b2/netbox_tunnels2/navigation.py#L27
In particular, the fact that it is using `netbox_tunnels`, not `netbox_tunnels2`. In the views file, the permissions are using `netbox_tunnels2`.
https://github.com/robertlynch3/netbox-tunnels2/blob/dc94e4d309ca762b56c773310b53791d4f9517b2/netbox_tunnels2/views.py#L35
