### ISSUE TITLE
configure tunnel between virtual machine

### ISSUE THREAD

**Issue by cj0duke** [robertlynch3/netbox-tunnels2#15]
The IP address can be selected from a device or VM.

For the device interface, would it be possible to select a VM interface? Thus having the possibility to create a tunnel between VMs and/or device/VM.

Thank you for this plugin.

**Comment by p-rintz** [comment]
Im gonna take a stab at this if you're not already working on it @robertlynch3

**Comment by robertlynch3** [comment]
That would be great. I originally used had VM interfaces as an option but I had an issue with it. 
I used [ryanmerolle/netbox-acls](https://github.com/ryanmerolle/netbox-acls/blob/adefefe9b1ca91f42352a3c7dd9682df54d15e6d/netbox_acls/models/access_lists.py#L107-L116) as a reference.
