### ISSUE TITLE
Add Plugin menu to top level menu

### ISSUE THREAD

**Issue by eu-tomas** [robertlynch3/netbox-tunnels2#21]
**Is your feature request related to a problem? Please describe.**
Right now to access the Tunnels plugin functionality users have to navigate through the plugins menu first to reach the Tunnels plugin. When you use this plugin a lot, this makes the presence of this functionality and the fact that important information is kept there much less obvious.

**Describe the solution you'd like**
Add the menu items for the Tunnels plugin to a Network Tunnels top level menu item either by default or by having a configuration file option for the plugin such as 'top_level_menu' to choose whether to add the items directly to the top level menu or not.

**Describe alternatives you've considered**
The only other alternative is to not implement this and navigate through the plugins menu first. It's still doable, but much less convenient when using this plugin often.

**Additional context**
I'm not very familiar with the NetBox Python code, but based on how other plugins do this, it seems to be mainly a matter of adding a variable menu to navigation.py that refers to a PluginMenu object containing the top level navigation menu item information and a reference to the group(s) of menu items that should be placed underneath.

**Comment by robertlynch3** [comment]
I think this is user dependent. I agree having a config option would be the best way to do this.
