### ISSUE TITLE
Topology visualisation for tunnels

### ISSUE THREAD

**Issue by normanord** [robertlynch3/netbox-tunnels2#6]
First of all, I love the plugin. I've got a bunch of sites connected with S2Ss and it's so odd, that tunnels are not representable in core Netbox.

Im using other plugin Topology Views to visualise all the connections inside a site and I was curious if You maybe have a plan to make those tunnels visualisable in some kind of way? I ofcours understand, that cross plugin compatibility is not Your concern, but just wanted to ask if maybe in a future You are planning that kind of feature?

**Comment by robertlynch3** [comment]
That is outside the scope of this plugin. One way to make this work would be to have physical interfaces that you create a connection for, but I don't think thats the best way.
