### ISSUE TITLE
Encryption domain network support

### ISSUE THREAD

**Issue by gpipito** [robertlynch3/netbox-tunnels2#7]
**Is your feature request related to a problem? Please describe.**
I would like support for encryption domains networks

**Describe the solution you'd like**
It would be good to have encryption domains fields related to networks in the ipam database.

**Describe alternatives you've considered**
The fields should be multiple choice items (cause you can have multiple networks for each encryption domain).

**Additional context**
![image](https://github.com/robertlynch3/netbox-tunnels2/assets/50398686/bc370cf0-6ac1-45e1-b0b3-65846a0b9a9f)
This is basically what i would like to have. A built-in relationship between tunnels and ipam prefixes instead of static custom fields.

**Comment by robertlynch3** [comment]
I don’t know if this falls into the model or not.

How I envisioned it is you’d have an inner IP tied to an interface and that interface is tied to the tunnel on side A or side B. The inner IP belongs to a VRF and that VRF is what is allowed between the tunnels. If you need something more strict, the custom fields allows you to do that. 

I am open to other comments.

**Comment by gpipito** [comment]
Hi,

thanks for your reply.

Actually I would like to store information about the private networks advertised/routed across the tunnel. I also don't want the data to be free-text but I want it to be related to a ipam prefix item.
The same could be said about the tunnel interface IP (something I did not think about before your reply), it would be nice to map it to a prefix item as well.

**Comment by p-rintz** [comment]
Would a custom field of type "Multiple Objects" not do what you want?

You can choose prefixes as the object and then it would allow you to directly link them to the tunnel.

**Comment by robertlynch3** [comment]
I am closing this. I agree with @p-rintz. The best thing to do is to create a custom field of type Multiple Objects for dcim.prefixes. You then can do a multi-select of your prefixes.
